version: '3'

services:
  mysql:
    container_name: parsers_mysql
    build:
      context: ./containers/mysql
      dockerfile: ./Dockerfile
    platform: 'linux/x86_64'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: parsers
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    restart: unless-stopped

  app:
    build:
      context: ./containers/app
      dockerfile: ./Dockerfile
    container_name: parsers_app
    environment:
      - HOST_DB=mysql
      - PYTHONUNBUFFERED=True
    volumes:
      - ./../app/:/usr/src/app
    ports:
      - "7000:7000"
    links:
      - mysql
    restart: unless-stopped